name: "size-limit-action"
description: "size-limit action"
author: "Andres Alvarez <a.alvarez.sor@gmail.com>"
branding:
  icon: "activity"
  color: "green"
inputs:
  github_token:
    required: true
    description: "a github access token"
  build_script:
    required: false
    description: 'a custom npm script to build'
  clean_script:
    required: false
    description: 'a npm script to clean up build directory'
  skip_step:
    required: false
    description: 'which step to skip, either "install" or "build"'
  directory:
    required: false
    description: "a custom subdirectory"
  windows_verbatim_arguments:
    required: false
    description: "exec `size-limit` with the option `windowsVerbatimArguments`"
    default: true
  main_branch:
    required: false
    default: master
    description: "The name of the main/protected branch"
  run_for_branch:
    required: false
    description: "This can be set to override the `main_branch` detection."
  threshold:
    required: false
    default: 0.0125
    description: "The percentage threshold for size changes before posting a comment"
  change_highlight_threshold:
    required: false
    default: 0
    description: "The percentage threshold for changes to be highlighted with an emoji"
runs:
  using: "node16"
  main: "dist/index.js"
